apiVersion: v2
name: erda
version: 2.3.0
appVersion: 2.3.0
description: An open-source platform bases on Kubernetes that can deploy microservice applications.
keywords:
  - Kubernetes
  - microservice
  - open-source
home: https://www.erda.cloud/
icon: https://github.com/erda-project/erda/raw/develop/docs/files/logo.jpg
sources:
  - https://github.com/erda-project/erda
  - https://github.com/erda-project/erda-infra
  - https://github.com/erda-project/erda-ui
type: application
dependencies:
  - name: common
    repository: https://charts.erda.cloud/erda
    tags:
      - erda-common
    version: 0.1.0
  - name: cassandra
    version: ~3.11.10
    condition: cassandra.enabled
    tags:
      - master
  - name: elasticsearch
    version: ~6.2.4
    condition: elasticsearch.enabled
    tags:
      - master
  - name: etcd
    version: ~3.3.15
    condition: etcd.enabled
    tags:
      - master
  - name: kafka
    version: ~1.1.0
    condition: kafka.enabled
    tags:
      - master
  - name: mysql
    version: ~5.7.34
    condition: mysql.enabled
    tags:
      - master
  - name: zookeeper
    version: ~3.4.13
    condition: zookeeper.enabled
    tags:
      - master
  - name: kms
    version: ~1.3.0
    condition: kms.enabled
    tags:
      - master
  - name: registry
    version: ~2.7.1
    condition: registry.enabled
    tags:
      - master
      - worker
  - name: sonar
    version: ~8.4.2
    condition: sonar.enabled
    tags:
      - master
  - name: volume-provisioner
    version: ~1.0.0
    condition: volume-provisioner.enabled
    tags:
      - master
      - worker
  - name: redis
    version: ~2.7.1
    condition: redis.enabled
    tags:
      - master
  - name: buildkitd
    version: ~0.9.2
    condition: buildkitd.enabled
    tags:
      - master
      - worker
maintainers:
  - name: Luobingli
    email: luobily@gmail.com
  - name: Wangzhuzhen
    email: zhuzhenwang1984@gmail.com
  - name: Liutianxiang
    email: root@viper.run
