{{/* vim: set filetype=mustache: */}}

{{/*
 TLS cert generatro job service account name
 */}}
{{- define "etcd.tlsCertServiceAccountName" -}}
{{- if .Values.tls.autoGenerated.rbac.create -}}
    {{- printf "erda-etcd" -}}
{{- else -}}
    {{ default "erda-etcd" .Values.tls.autoGenerated.serviceAccountName }}
{{- end -}}
{{- end -}}
